import { useState } from 'react'
import { Link, useNavigate } from 'react-router-dom'

const faq=[['What is PayLink?','A clean, branded UPI payment page that you can share anywhere.'],['Is payment secure?','Payments open in the customer’s own UPI app. PayLink does not hold funds.'],['Do customers need an account?','No. They can scan your QR code or open the payment link.']]
export function PayLinkHome(){const nav=useNavigate(),[loading,setLoading]=useState(false),start=()=>{setLoading(true);setTimeout(()=>nav('/login'),1750)};return <main className="pl-home">{loading&&<Loader/>}<nav className="pl-nav"><Link to="/" className="pl-brand"><i>P</i>PayLink</Link><div><a href="#features">Features</a><a href="#security">Security</a><a href="#faq">FAQ</a></div><button onClick={start}>Get Started <b>→</b></button></nav><section className="pl-hero"><div><p>ONE LINK. SIMPLE PAYMENTS.</p><h1>Make every payment feel <em>professional.</em></h1><span>PayLink gives independent sellers a clean, branded way to collect UPI payments and share their offering online.</span><aside><button onClick={start}>Create your PayLink <b>→</b></button><a href="#how">See how it works</a></aside><small>✓ Secure UPI links　 ✓ No code required　 ✓ Ready in minutes</small></div><Preview/></section><section className="pl-section" id="features"><p>BUILT FOR INDEPENDENT SELLERS</p><h2>Everything you need, without checkout clutter.</h2><div className="pl-cards"><Card icon="✦" title="Branded page" text="Your logo, cover, colours and product details in one focused page."/><Card icon="⌁" title="Instant UPI" text="A simple link and QR code that work with any UPI app."/><Card icon="↗" title="Clear activity" text="Track views, QR scans and payment-click activity."/></div></section><section className="pl-why" id="how"><div><p>WHY PAYLINK</p><h2>Less setup. More confidence.</h2><span>Built for courses, services and small businesses that want a premium payment experience.</span></div><ol><li><b>01</b><strong>Add your payment details<small>Set your UPI ID, product and amount.</small></strong></li><li><b>02</b><strong>Personalise your page<small>Choose a visual style that fits your brand.</small></strong></li><li><b>03</b><strong>Publish and share<small>Send one polished link anywhere.</small></strong></li></ol></section><section className="pl-security" id="security"><p>SECURITY BY DESIGN</p><h2>Your payment instructions stay clear and in your control.</h2><div><Card title="UPI-first" text="Payments open in the customer’s own payment app."/><Card title="Protected workspace" text="Your editor is secured with your PayLink account."/><Card title="Privacy-aware" text="PayLink never stores payment funds."/></div></section><section className="pl-faq" id="faq"><p>FAQ</p><h2>Good to know.</h2>{faq.map(x=><details key={x[0]}><summary>{x[0]} <b>+</b></summary><span>{x[1]}</span></details>)}</section><section className="pl-cta"><p>READY WHEN YOU ARE</p><h2>Give your next payment a better link.</h2><button onClick={start}>Get Started <b>→</b></button></section><Footer/></main>}
function Loader(){return <div className="pl-loader"><i>P</i><b>Loading your workspace...</b><div><span/></div><small>Preparing your secure PayLink space</small></div>}
function Preview(){return <article className="pl-preview"><header>PAYLINK PAGE <b>•••</b></header><div/><main><i>P</i><small>PAYMENT FOR</small><h3>Design workshop</h3><strong>₹499</strong><em>▦</em><button>Pay with UPI <b>→</b></button></main></article>}
function Card({icon,title,text}){return <article>{icon&&<i>{icon}</i>}<h3>{title}</h3><span>{text}</span></article>}
function Footer(){return <footer className="pl-footer"><div><Link to="/" className="pl-brand"><i>P</i>PayLink</Link><span>Simple, polished payment links for independent businesses.</span><small>Built by Siddharth Deshmukh</small></div><div><b>Product</b><a href="#features">Features</a><a href="#how">How it works</a><a href="#faq">Help center</a></div><div><b>Company</b><a href="mailto:hello@paylink.app">Contact us</a><Link to="/legal/privacy">Privacy policy</Link><Link to="/legal/terms">Terms & conditions</Link><Link to="/legal/cookies">Cookie policy</Link></div><div><b>Social</b><a href="#linkedin">LinkedIn</a><a href="#instagram">Instagram</a><a href="#twitter">X / Twitter</a></div></footer>}
